### ISSUE TITLE
Link232-Wifi/Swiftlink Dot Clock.

### ISSUE THREAD

**Issue by dabonetn** [randyrossi/vicii-kawari#7]
Testing today with a Link232-Wifi Cart and a internal cart, they seem to work fine even when the board is running
at a different non pll clock, so Pal or NTSC generated from the Kawari or motherboard for NTSC and Kawari for PAL still seems to work fine. 

I've downloaded around 10 d64s with no errors changing between NTSC and PAL,, mb clock and Kawari clock.

**Comment by randyrossi** [comment]
Thanks for the report.  When I did my testing, the Link232-Wifi cart would randomly fail using the on-board oscillators.  It's good to hear it works consistently for you but I will still caution users this may still fail.  Closing since it's not an issue (or at least possibly a known/documented one).
